version: '3.3'

services:
  mongodb :
    container_name: yapi_mongodb
    image: mongo:4.4.6
    volumes:
        - $PWD/mongo/db:/data/db
        - $PWD/mongo/log:/var/log/mongodb
    ports:
      - 27017:27017
    # command: --auth

  yapi:
    container_name: yapi_main
    image: xcbeyond/yapi:1.9.2
    volumes:
        - $PWD/yapi-src:/yapi
    ports:
      - 3333:3000
    depends_on: 
      - mongodb
